package Parser;
/* CVS $Id: $ */

import org.apache.jena.rdf.model.*;

/**
 * Vocabulary definitions from https://www.w3.org/ns/odrl/2/ODRL22.rdf
 * @author Auto-generated by schemagen
 */
public class ODRL_vocab {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static final Model M_MODEL = ModelFactory.createDefaultModel();

    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://www.w3.org/ns/odrl/2/";

    /** <p>The namespace of the vocabulary as a string</p>
     * @return namespace as String
     * @see #NS */
    public static String getURI() {return NS;}

    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = M_MODEL.createResource( NS );

    /** <p>The ontology's owl:versionInfo as a string</p> */
    public static final String VERSION_INFO = "2.2";

    public static final Property action = M_MODEL.createProperty( "http://www.w3.org/ns/odrl/2/action" );

    public static final Property and = M_MODEL.createProperty( "http://www.w3.org/ns/odrl/2/and" );

    public static final Property andSequence = M_MODEL.createProperty( "http://www.w3.org/ns/odrl/2/andSequence" );

    public static final Property assignee = M_MODEL.createProperty( "http://www.w3.org/ns/odrl/2/assignee" );

    public static final Property assigneeOf = M_MODEL.createProperty( "http://www.w3.org/ns/odrl/2/assigneeOf" );

    public static final Property assigner = M_MODEL.createProperty( "http://www.w3.org/ns/odrl/2/assigner" );

    public static final Property assignerOf = M_MODEL.createProperty( "http://www.w3.org/ns/odrl/2/assignerOf" );

    public static final Property attributedParty = M_MODEL.createProperty( "http://www.w3.org/ns/odrl/2/attributedParty" );

    public static final Property attributingParty = M_MODEL.createProperty( "http://www.w3.org/ns/odrl/2/attributingParty" );

    public static final Property compensatedParty = M_MODEL.createProperty( "http://www.w3.org/ns/odrl/2/compensatedParty" );

    public static final Property compensatingParty = M_MODEL.createProperty( "http://www.w3.org/ns/odrl/2/compensatingParty" );

    public static final Property conflict = M_MODEL.createProperty( "http://www.w3.org/ns/odrl/2/conflict" );

    public static final Property consentedParty = M_MODEL.createProperty( "http://www.w3.org/ns/odrl/2/consentedParty" );

    public static final Property consentingParty = M_MODEL.createProperty( "http://www.w3.org/ns/odrl/2/consentingParty" );

    public static final Property consequence = M_MODEL.createProperty( "http://www.w3.org/ns/odrl/2/consequence" );

    public static final Property constraint = M_MODEL.createProperty( "http://www.w3.org/ns/odrl/2/constraint" );

    public static final Property contractedParty = M_MODEL.createProperty( "http://www.w3.org/ns/odrl/2/contractedParty" );

    public static final Property contractingParty = M_MODEL.createProperty( "http://www.w3.org/ns/odrl/2/contractingParty" );

    public static final Property dataType = M_MODEL.createProperty( "http://www.w3.org/ns/odrl/2/dataType" );

    public static final Property duty = M_MODEL.createProperty( "http://www.w3.org/ns/odrl/2/duty" );

    public static final Property failure = M_MODEL.createProperty( "http://www.w3.org/ns/odrl/2/failure" );

    public static final Property function = M_MODEL.createProperty( "http://www.w3.org/ns/odrl/2/function" );

    public static final Property hasPolicy = M_MODEL.createProperty( "http://www.w3.org/ns/odrl/2/hasPolicy" );

    public static final Property implies = M_MODEL.createProperty( "http://www.w3.org/ns/odrl/2/implies" );

    public static final Property includedIn = M_MODEL.createProperty( "http://www.w3.org/ns/odrl/2/includedIn" );

    public static final Property informedParty = M_MODEL.createProperty( "http://www.w3.org/ns/odrl/2/informedParty" );

    public static final Property informingParty = M_MODEL.createProperty( "http://www.w3.org/ns/odrl/2/informingParty" );

    public static final Property inheritAllowed = M_MODEL.createProperty( "http://www.w3.org/ns/odrl/2/inheritAllowed" );

    public static final Property inheritFrom = M_MODEL.createProperty( "http://www.w3.org/ns/odrl/2/inheritFrom" );

    public static final Property inheritRelation = M_MODEL.createProperty( "http://www.w3.org/ns/odrl/2/inheritRelation" );

    public static final Property leftOperand = M_MODEL.createProperty( "http://www.w3.org/ns/odrl/2/leftOperand" );

    public static final Property obligation = M_MODEL.createProperty( "http://www.w3.org/ns/odrl/2/obligation" );

    public static final Property operand = M_MODEL.createProperty( "http://www.w3.org/ns/odrl/2/operand" );

    public static final Property operator = M_MODEL.createProperty( "http://www.w3.org/ns/odrl/2/operator" );

    public static final Property or = M_MODEL.createProperty( "http://www.w3.org/ns/odrl/2/or" );

    public static final Property output = M_MODEL.createProperty( "http://www.w3.org/ns/odrl/2/output" );

    public static final Property partOf = M_MODEL.createProperty( "http://www.w3.org/ns/odrl/2/partOf" );

    public static final Property payeeParty = M_MODEL.createProperty( "http://www.w3.org/ns/odrl/2/payeeParty" );

    public static final Property permission = M_MODEL.createProperty( "http://www.w3.org/ns/odrl/2/permission" );

    public static final Property profile = M_MODEL.createProperty( "http://www.w3.org/ns/odrl/2/profile" );

    public static final Property prohibition = M_MODEL.createProperty( "http://www.w3.org/ns/odrl/2/prohibition" );

    public static final Property proximity = M_MODEL.createProperty( "http://www.w3.org/ns/odrl/2/proximity" );

    public static final Property refinement = M_MODEL.createProperty( "http://www.w3.org/ns/odrl/2/refinement" );

    public static final Property relation = M_MODEL.createProperty( "http://www.w3.org/ns/odrl/2/relation" );

    public static final Property remedy = M_MODEL.createProperty( "http://www.w3.org/ns/odrl/2/remedy" );

    public static final Property rightOperand = M_MODEL.createProperty( "http://www.w3.org/ns/odrl/2/rightOperand" );

    public static final Property rightOperandReference = M_MODEL.createProperty( "http://www.w3.org/ns/odrl/2/rightOperandReference" );

    public static final Property scope = M_MODEL.createProperty( "http://www.w3.org/ns/odrl/2/scope" );

    public static final Property source = M_MODEL.createProperty( "http://www.w3.org/ns/odrl/2/source" );

    public static final Property status = M_MODEL.createProperty( "http://www.w3.org/ns/odrl/2/status" );

    public static final Property target = M_MODEL.createProperty( "http://www.w3.org/ns/odrl/2/target" );

    public static final Property timedCount = M_MODEL.createProperty( "http://www.w3.org/ns/odrl/2/timedCount" );

    public static final Property trackedParty = M_MODEL.createProperty( "http://www.w3.org/ns/odrl/2/trackedParty" );

    public static final Property trackingParty = M_MODEL.createProperty( "http://www.w3.org/ns/odrl/2/trackingParty" );

    public static final Property uid = M_MODEL.createProperty( "http://www.w3.org/ns/odrl/2/uid" );

    public static final Property undefined = M_MODEL.createProperty( "http://www.w3.org/ns/odrl/2/undefined" );

    public static final Property unit = M_MODEL.createProperty( "http://www.w3.org/ns/odrl/2/unit" );

    public static final Property xone = M_MODEL.createProperty( "http://www.w3.org/ns/odrl/2/xone" );

    public static final Resource Action = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/Action" );

    public static final Resource Agreement = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/Agreement" );

    public static final Resource Assertion = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/Assertion" );

    public static final Resource Asset = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/Asset" );

    public static final Resource AssetCollection = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/AssetCollection" );

    public static final Resource AssetScope = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/AssetScope" );

    public static final Resource ConflictTerm = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/ConflictTerm" );

    public static final Resource Constraint = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/Constraint" );

    public static final Resource Duty = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/Duty" );

    public static final Resource LeftOperand = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/LeftOperand" );

    public static final Resource LogicalConstraint = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/LogicalConstraint" );

    public static final Resource Offer = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/Offer" );

    public static final Resource Operator = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/Operator" );

    public static final Resource Party = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/Party" );

    public static final Resource PartyCollection = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/PartyCollection" );

    public static final Resource PartyScope = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/PartyScope" );

    public static final Resource Permission = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/Permission" );

    public static final Resource Policy = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/Policy" );

    public static final Resource Privacy = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/Privacy" );

    public static final Resource Prohibition = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/Prohibition" );

    public static final Resource Request = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/Request" );

    public static final Resource RightOperand = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/RightOperand" );

    public static final Resource Rule = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/Rule" );

    public static final Resource Set = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/Set" );

    public static final Resource Ticket = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/Ticket" );

    public static final Resource UndefinedTerm = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/UndefinedTerm" );

    public static final Resource Attribution = M_MODEL.createResource( "http://creativecommons.org/ns#Attribution" );

    public static final Resource CommericalUse = M_MODEL.createResource( "http://creativecommons.org/ns#CommericalUse" );

    public static final Resource DerivativeWorks = M_MODEL.createResource( "http://creativecommons.org/ns#DerivativeWorks" );

    public static final Resource Distribution = M_MODEL.createResource( "http://creativecommons.org/ns#Distribution" );

    public static final Resource Notice = M_MODEL.createResource( "http://creativecommons.org/ns#Notice" );

    public static final Resource Reproduction = M_MODEL.createResource( "http://creativecommons.org/ns#Reproduction" );

    public static final Resource ShareAlike = M_MODEL.createResource( "http://creativecommons.org/ns#ShareAlike" );

    public static final Resource Sharing = M_MODEL.createResource( "http://creativecommons.org/ns#Sharing" );

    public static final Resource SourceCode = M_MODEL.createResource( "http://creativecommons.org/ns#SourceCode" );

    public static final Resource actionConcepts = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/#actionConcepts" );

    public static final Resource actions = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/#actions" );

    public static final Resource actionsCommon = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/#actionsCommon" );

    public static final Resource assetConcepts = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/#assetConcepts" );

    public static final Resource assetParty = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/#assetParty" );

    public static final Resource assetRelations = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/#assetRelations" );

    public static final Resource assetRelationsCommon = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/#assetRelationsCommon" );

    public static final Resource conflictConcepts = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/#conflictConcepts" );

    public static final Resource constraintLeftOperandCommon = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/#constraintLeftOperandCommon" );

    public static final Resource constraintLogicalOperands = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/#constraintLogicalOperands" );

    public static final Resource constraintRelationalOperators = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/#constraintRelationalOperators" );

    public static final Resource constraintRightOpCommon = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/#constraintRightOpCommon" );

    public static final Resource constraints = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/#constraints" );

    public static final Resource deprecatedTerms = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/#deprecatedTerms" );

    public static final Resource duties = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/#duties" );

    public static final Resource logicalConstraints = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/#logicalConstraints" );

    public static final Resource partyConcepts = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/#partyConcepts" );

    public static final Resource partyRoles = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/#partyRoles" );

    public static final Resource partyRolesCommon = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/#partyRolesCommon" );

    public static final Resource permissions = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/#permissions" );

    public static final Resource policyConcepts = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/#policyConcepts" );

    public static final Resource policySubClasses = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/#policySubClasses" );

    public static final Resource policySubClassesCommon = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/#policySubClassesCommon" );

    public static final Resource prohibitions = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/#prohibitions" );

    public static final Resource ruleConcepts = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/#ruleConcepts" );

    public static final Resource All = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/All" );

    public static final Resource All2ndConnections = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/All2ndConnections" );

    public static final Resource AllConnections = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/AllConnections" );

    public static final Resource AllGroups = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/AllGroups" );

    public static final Resource Group = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/Group" );

    public static final Resource Individual = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/Individual" );

    public static final Resource absolutePosition = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/absolutePosition" );

    public static final Resource absoluteSize = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/absoluteSize" );

    public static final Resource absoluteSpatialPosition = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/absoluteSpatialPosition" );

    public static final Resource absoluteTemporalPosition = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/absoluteTemporalPosition" );

    public static final Resource acceptTracking = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/acceptTracking" );

    public static final Resource adHocShare = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/adHocShare" );

    public static final Resource aggregate = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/aggregate" );

    public static final Resource annotate = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/annotate" );

    public static final Resource anonymize = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/anonymize" );

    public static final Resource append = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/append" );

    public static final Resource appendTo = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/appendTo" );

    public static final Resource archive = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/archive" );

    public static final Resource attachPolicy = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/attachPolicy" );

    public static final Resource attachSource = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/attachSource" );

    public static final Resource attribute = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/attribute" );

    public static final Resource commercialize = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/commercialize" );

    public static final Resource compensate = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/compensate" );

    public static final Resource concurrentUse = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/concurrentUse" );

    public static final Resource copy = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/copy" );

    public static final Resource core = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/core" );

    public static final Resource count = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/count" );

    public static final Resource dateTime = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/dateTime" );

    public static final Resource delayPeriod = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/delayPeriod" );

    public static final Resource delete = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/delete" );

    public static final Resource deliveryChannel = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/deliveryChannel" );

    public static final Resource derive = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/derive" );

    public static final Resource device = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/device" );

    public static final Resource digitize = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/digitize" );

    public static final Resource display = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/display" );

    public static final Resource distribute = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/distribute" );

    public static final Resource elapsedTime = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/elapsedTime" );

    public static final Resource ensureExclusivity = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/ensureExclusivity" );

    public static final Resource eq = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/eq" );

    public static final Resource event = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/event" );

    public static final Resource execute = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/execute" );

    public static final Resource export = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/export" );

    public static final Resource extract = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/extract" );

    public static final Resource extractChar = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/extractChar" );

    public static final Resource extractPage = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/extractPage" );

    public static final Resource extractWord = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/extractWord" );

    public static final Resource fileFormat = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/fileFormat" );

    public static final Resource give = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/give" );

    public static final Resource grantUse = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/grantUse" );

    public static final Resource gt = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/gt" );

    public static final Resource gteq = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/gteq" );

    public static final Resource hasPart = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/hasPart" );

    public static final Resource ignore = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/ignore" );

    public static final Resource include = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/include" );

    public static final Resource index = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/index" );

    public static final Resource industry = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/industry" );

    public static final Resource inform = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/inform" );

    public static final Resource install = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/install" );

    public static final Resource invalid = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/invalid" );

    public static final Resource isA = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/isA" );

    public static final Resource isAllOf = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/isAllOf" );

    public static final Resource isAnyOf = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/isAnyOf" );

    public static final Resource isNoneOf = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/isNoneOf" );

    public static final Resource isPartOf = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/isPartOf" );

    public static final Resource language = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/language" );

    public static final Resource lease = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/lease" );

    public static final Resource lend = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/lend" );

    public static final Resource license = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/license" );

    public static final Resource lt = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/lt" );

    public static final Resource lteq = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/lteq" );

    public static final Resource media = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/media" );

    public static final Resource meteredTime = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/meteredTime" );

    public static final Resource modify = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/modify" );

    public static final Resource move = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/move" );

    public static final Resource neq = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/neq" );

    public static final Resource nextPolicy = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/nextPolicy" );

    public static final Resource obtainConsent = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/obtainConsent" );

    public static final Resource pay = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/pay" );

    public static final Resource payAmount = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/payAmount" );

    public static final Resource percentage = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/percentage" );

    public static final Resource perm = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/perm" );

    public static final Resource play = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/play" );

    public static final Resource policyUsage = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/policyUsage" );

    public static final Resource present = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/present" );

    public static final Resource preview = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/preview" );

    public static final Resource print = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/print" );

    public static final Resource product = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/product" );

    public static final Resource prohibit = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/prohibit" );

    public static final Resource purpose = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/purpose" );

    public static final Resource read = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/read" );

    public static final Resource recipient = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/recipient" );

    public static final Resource relativePosition = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/relativePosition" );

    public static final Resource relativeSize = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/relativeSize" );

    public static final Resource relativeSpatialPosition = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/relativeSpatialPosition" );

    public static final Resource relativeTemporalPosition = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/relativeTemporalPosition" );

    public static final Resource reproduce = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/reproduce" );

    public static final Resource resolution = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/resolution" );

    public static final Resource reviewPolicy = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/reviewPolicy" );

    public static final Resource secondaryUse = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/secondaryUse" );

    public static final Resource sell = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/sell" );

    public static final Resource share = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/share" );

    public static final Resource shareAlike = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/shareAlike" );

    public static final Resource spatial = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/spatial" );

    public static final Resource spatialCoordinates = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/spatialCoordinates" );

    public static final Resource stream = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/stream" );

    public static final Resource support = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/support" );

    public static final Resource synchronize = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/synchronize" );

    public static final Resource system = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/system" );

    public static final Resource systemDevice = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/systemDevice" );

    public static final Resource textToSpeech = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/textToSpeech" );

    public static final Resource timeInterval = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/timeInterval" );

    public static final Resource transfer = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/transfer" );

    public static final Resource transform = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/transform" );

    public static final Resource translate = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/translate" );

    public static final Resource uninstall = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/uninstall" );

    public static final Resource unitOfCount = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/unitOfCount" );

    public static final Resource use = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/use" );

    public static final Resource version = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/version" );

    public static final Resource virtualLocation = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/virtualLocation" );

    public static final Resource watermark = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/watermark" );

    public static final Resource write = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/write" );

    public static final Resource writeTo = M_MODEL.createResource( "http://www.w3.org/ns/odrl/2/writeTo" );

    //Aggiunto manualmente
    public static final Property  type = M_MODEL.createProperty( "http://www.w3.org/1999/02/22-rdf-syntax-ns#type");


}
